spring:
    application:
        name: desktopfs

network-drive:
    base-url: ${NETWORK_DRIVE_BASE_URL}

    cache:
        expire-after-write: ${NETWORK_DRIVE_CACHE_EXPIRE_AFTER_WRITE}
        max-size: ${NETWORK_DRIVE_CACHE_MAX_SIZE}
